kind: pipeline
name : LLVM Toolchain Compiler
version: rev1.5_template
steps:
 - name: LLVM-tc Compilation
   image: xyzuan/xdocker:latest
   environment:
     LLVM_NAME:
       from_secret: LLVM_NAME
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     GH_USERNAME:
       from_secret: GH_USERNAME
     GH_EMAIL:
       from_secret: GH_EMAIL
     GH_TOKEN:
       from_secret: GH_TOKEN
     GH_PUSH_REPO_URL:
       from_secret: GH_PUSH_REPO_URL
   commands:
     - apt update -y && apt install -y --no-install-recommends cmake ninja-build python3-pip libffi-dev python3-dev  clang bc gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi ncurses-dev
     - bash llvm-tc_build.sh
